openapi: 3.0.0
info:
  title: Project Management App
  description: Anna Lopez Ribo
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/
    description: Localhost development server
components:
  securitySchemes:
    ApiKeyAuth: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Todo:
      type: object
      properties:
        todo:
          type: string
        author:
          type: string
paths:
  /todos:
    get:
      summary: Retrieve all Todos
      tags:
        - Todos
      description: Retrieves a list of all the Todos.
      responses:
        200:
          description: A list of artist JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
