/* eslint-disable vue/multi-word-component-names */
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import './axios.js';
import TurnOffAutocomplete from 'vue-turn-off-autocomplete';
import ConfirmationService from 'primevue/confirmationservice';
// PrimeVue UI
import PrimeVue from 'primevue/config';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Password from 'primevue/password';
import Dialog from 'primevue/dialog';
import ProgressBar from 'primevue/progressbar';
import ToastService from 'primevue/toastservice';
import Toast from 'primevue/toast';
import Message from 'primevue/message';
import Toolbar from 'primevue/toolbar';
import Avatar from 'primevue/avatar';
import AvatarGroup from 'primevue/avatargroup';
import Dropdown from 'primevue/dropdown';
import ConfirmDialog from 'primevue/confirmdialog';
import 'primevue/resources/primevue.min.css'; //core css
import 'primeicons/primeicons.css'; //icons
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import Row from 'primevue/row';
import PanelMenu from 'primevue/panelmenu';
import Fieldset from 'primevue/fieldset';
import Panel from 'primevue/panel';
import Chip from 'primevue/chip';
import Tag from 'primevue/tag';
import Card from 'primevue/card';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import PickList from 'primevue/picklist';
import Calendar from 'primevue/calendar';
import InputNumber from 'primevue/inputnumber';
import ScrollTop from 'primevue/scrolltop';
import 'primevue/resources/themes/bootstrap4-light-purple/theme.css';

const app = createApp(App);
app.use(router);
app.use(PrimeVue);
app.use(ToastService);

app.use(TurnOffAutocomplete);
app.use(ConfirmationService);
app.component('InputText', InputText);
app.component('Textarea', Textarea);
app.component('Password', Password);
app.component('Button', Button);
app.component('Dialog', Dialog);
app.component('Toast', Toast);
app.component('Message', Message);
app.component('Avatar', Avatar);
app.component('AvatarGroup', AvatarGroup);
app.component('DataTable', DataTable);
app.component('Column', Column);
app.component('ColumnGroup', ColumnGroup);
app.component('Row', Row);
app.component('Panel', Panel);
app.component('PanelMenu', PanelMenu);
app.component('Fieldset', Fieldset);
app.component('ProgressBar', ProgressBar);
app.component('Chip', Chip);
app.component('Card', Card);
app.component('TabView', TabView);
app.component('TabPanel', TabPanel);
app.component('Toolbar', Toolbar);
app.component('Dropdown', Dropdown);
app.component('PickList', PickList);
app.component('Calendar', Calendar);
app.component('ScrollTop', ScrollTop);
app.component('InputNumber', InputNumber);
app.component('ConfirmDialog', ConfirmDialog);
app.component('Tag', Tag);
app.mount('#app');
